### ISSUE TITLE
cannot access protected method java.lang.Class com.appsflyer.internal.AFa1zSDK

### ISSUE THREAD

**Issue by viclee888** [AppsFlyerSDK/appsflyer-android-app#20] opened 2023-02-07 02:30 UTC
Caused by java.lang.IllegalAccessException
Class java.lang.Class<java.lang.reflect.Method> cannot access protected method java.lang.Class com.appsflyer.internal.AFa1zSDK$$.loadClass(java.lang.String, boolean) of class java.lang.Class<com.appsflyer.internal.AFa1zSDK$$>

com.appsflyer:af-android-sdk:6.9.4
Samsung Galaxy A70. Android 8.1.0

**Comment by ariko-sp** [comment] 2023-04-27 09:52
Same

**Comment by tolgakartal** [comment] 2023-05-02 08:14
same 

```
Fatal Exception: java.lang.Error: java.lang.IllegalAccessException: Class java.lang.Class<java.lang.reflect.Method> cannot access protected  method java.lang.Class com.appsflyer.internal.AFa1zSDK$$.loadClass(java.lang.String, boolean) of class java.lang.Class<com.appsflyer.internal.AFa1zSDK$$>
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1168)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
```

**Comment by stri8ed** [comment] 2023-05-16 18:38
Noticed 3 instances of this. All of them on Android 11

- Mi 9X
- Motorola One Vision

```
Caused by java.lang.IllegalAccessException: Class java.lang.Class<java.lang.reflect.Method> cannot access protected  method java.lang.Class com.appsflyer.internal.AFa1xSDK$$.loadClass(java.lang.String, boolean) of class java.lang.Class<com.appsflyer.internal.AFa1xSDK$$>
       at java.lang.reflect.Method.invokeImpl(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:425)
       at com.appsflyer.internal.AFa1xSDK$$.valueOf(:100)
       at com.appsflyer.internal.AFa1xSDK$$.AFKeystoreWrapper(:26)
       at java.lang.reflect.Method.invokeImpl(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:425)
       at com.appsflyer.internal.AFa1ySDK.values(:106)
       at com.appsflyer.internal.AFc1xSDK.AFInAppEventType(SourceFile:142)
       at com.appsflyer.internal.AFd1tSDK.AFKeystoreWrapper(SourceFile:65)
       at com.appsflyer.internal.AFc1hSDK.valueOf(SourceFile:113)
       at com.appsflyer.internal.AFc1mSDK$5.run(:109)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
```
Given the stack track, I supect its probably being triggered in this call:

`AppsFlyerLib.getInstance().logEvent(applicationContext, AFInAppEventType.COMPLETE_REGISTRATION, props)`

**Comment by michal-chojnacki** [comment] 2023-06-01 13:55
I have the same issue in my apps. It occurs only for Android 11 on devices:
 - Huawei Enjoy 9s
 - Mi 9X
 - Samsung Galaxy A70
 - Motorola One Vision
 
 Stacktrace:
```
IllegalAccessException: Class java.lang.Class<java.lang.reflect.Method> cannot access protected  method java.lang.Class com.appsflyer.internal.AFa1wSDK$$.loadClass(java.lang.String, boolean) of class java.lang.Class<com.appsflyer.internal.AFa1wSDK$$>
    at java.lang.reflect.Method.invokeImpl(Method.java)
    at java.lang.reflect.Method.invoke(Method.java:425)
    at com.appsflyer.internal.AFa1wSDK$$.values
    at com.appsflyer.internal.AFa1wSDK$$.AFKeystoreWrapper
    at java.lang.reflect.Method.invokeImpl(Method.java)
```

**Comment by ariko-sp** [comment] 2023-06-03 09:47
?

**Comment by ariko-sp** [comment] 2023-06-03 09:47
same

**Comment by renanbronchart** [comment] 2023-06-05 20:48
Same please help.

**Comment by deepak-agendaboa** [comment] 2023-06-13 06:56
I also have the same crash in Crashlytics. All of the crashes says the device is rooted. 
![Screen Shot 2023-06-13 at 12 26 05 PM](https://github.com/AppsFlyerSDK/appsflyer-android-app/assets/120708752/94febab3-2552-4ba3-ad69-5ca2fbe974e3)

**Comment by pazlavi** [comment] 2023-06-26 07:52
Hi all, 
Please update the SDK to 6.11.1 and let us know if the issue is solved.

**Comment by shoheikawano** [comment] 2023-06-27 00:23
@pazlavi 
Updated to 6.11.1, and It seems it is not resolved yet

**Comment by pazlavi** [comment] 2023-06-27 07:58
@shoheikawano 
Can you please share the stacktrace, affected devices, and OS versions?

**Comment by shoheikawano** [comment] 2023-06-28 02:44
so far happens for Android 10, 11
it seems that it is rare case to happen, but when it happens it is going to be repetitive crashes.

stacktrace:
```
Fatal Exception: java.lang.UnsatisfiedLinkError: com.appsflyer.internal.AFa1zSDK$$@173dbfc couldn't find "libcda739.so"
       at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
       at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
       at java.lang.System.loadLibrary(System.java:1667)
       at com.appsflyer.internal.AFa1mSDK$2286.<clinit>(:2)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.appsflyer.internal.AFa1dSDK.values(SourceFile:50177)
       at com.appsflyer.internal.AFa1dSDK.<clinit>(:142)
       at com.appsflyer.internal.AFa1dSDK.valueOf(SourceFile:242)
       at com.appsflyer.AppsFlyerLib.getInstance()
```

**Comment by araujotadeu** [comment] 2023-06-29 14:59
Same here, extra information that may help. Looks like in all my cases are devices with low battery right after boot.

**Comment by chapsan2001** [comment] 2023-06-30 08:13
Yep, same here. Only rooted devices with Android 11 were affected. Seems like vendor does not matter, I have Samsung, Vivo, Motorola, Huawei and Xiaomi.

**Comment by pazlavi** [comment] 2023-07-02 09:54
@shoheikawano @araujotadeu @chapsan2001 and everyone who experienced this issue, can you please share the following?
* Are they any patterns other than the Android version? For example, do you know if the specific devices are low on memory/disk space? Or if the devices all have some specific locale?
* Is it crashing multiple times per app user? For example, for single app user, does it occur once the app crashes, and then the next time the app opens fine? Or does it happen every time the user opens the app?
* Can you reproduce it? If so, please share the steps, snippets, or a sample project if possible. (you can share it with our support team)
* Share with our support team at support@appsflyer.com APK that experience this crash.

**Comment by londhep** [comment] 2023-07-13 13:11
Hello @pazlavi I wanted to check if there is any update on this issue.
I have also seen a crash in Crashlytics for Android 11 and with rooted devices.
Looks like from crash instances, it's not happening for multiple times per user as there is one event per user registered.

**Comment by pazlavi** [comment] 2023-07-13 13:59
Hi @londhep, 
Unfortunately, we couldn't find the root cause of this crash yet. It would be really helpful for our investigation if you could share with our support team ([support@appsflyer.com](mailto:support@appsflyer.com)) the affected APK  stack traces and all other relevant info you can share (devices, OS version, etc.) 
Thanks.

**Comment by vanLesson** [comment] 2023-07-14 07:20
same issue 11 Android  OnePlus8Pro 
```
Caused by java.lang.IllegalAccessException: Class java.lang.Class<java.lang.reflect.Method> cannot access protected  method java.lang.Class com.appsflyer.internal.AFa1xSDK$$.loadClass(java.lang.String, boolean) of class java.lang.Class<com.appsflyer.internal.AFa1xSDK$$>
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:423)
       at com.appsflyer.internal.AFa1xSDK$$.AFInAppEventType(:100)
       at com.appsflyer.internal.AFa1xSDK$$.AFInAppEventParameterName(:26)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:423)
       at com.appsflyer.internal.AFa1vSDK.AFInAppEventParameterName(:124)
       at com.appsflyer.internal.AFc1kSDK.AFInAppEventType(:140)
       at com.appsflyer.internal.AFd1cSDK.AFInAppEventParameterName(:87)
       at com.appsflyer.internal.AFd1iSDK.valueOf(:114)
       at com.appsflyer.internal.AFd1pSDK$5.run(:109)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
       
```

**Comment by pazlavi** [comment] 2023-07-14 08:17
@vanLesson, which SDK version did you use?

**Comment by vanLesson** [comment] 2023-07-14 08:20
@pazlavi i'm using version ^6.10.3 but it`s react-native-appsflyer

**Comment by aidan-24com** [comment] 2023-07-14 08:21
same issue here.

looks like we started getting this once we targeted android 13.

also looks like `loadClass` is restricted when targeting API 33?

https://developer.android.com/about/versions/13/changes/non-sdk-13

We are using the react-native package, but the android SDK version was resolved to 6.9.4


```
Fatal Exception: java.lang.Error: java.lang.IllegalAccessException: Class java.lang.Class<java.lang.reflect.Method> cannot access protected  method java.lang.Class com.appsflyer.internal.AFa1zSDK$$.loadClass(java.lang.String, boolean) of class java.lang.Class<com.appsflyer.internal.AFa1zSDK$$>
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1173)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)

Caused by java.lang.IllegalAccessException: Class java.lang.Class<java.lang.reflect.Method> cannot access protected  method java.lang.Class com.appsflyer.internal.AFa1zSDK$$.loadClass(java.lang.String, boolean) of class java.lang.Class<com.appsflyer.internal.AFa1zSDK$$>
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:423)
       at com.appsflyer.internal.AFa1zSDK$$.valueOf(:100)
       at com.appsflyer.internal.AFa1zSDK$$.AFKeystoreWrapper(:20)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:423)
       at com.appsflyer.internal.AFa1wSDK.values(:125)
       at com.appsflyer.internal.AFc1vSDK.AFKeystoreWrapper(:143)
       at com.appsflyer.internal.AFd1rSDK.AFKeystoreWrapper(:65)
       at com.appsflyer.internal.AFd1vSDK.values(:113)
       at com.appsflyer.internal.AFc1gSDK$1.run(:109)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
```

**Comment by markofevil3** [comment] 2023-07-18 03:53
Same issue with our project.
Using Appsflyer for Unity - v6.9.4

Attached stacktrace log file from Firebase

[com.alleylabs.battlegrounds_issue_058b6e64d49556d6cd96eb4c064927f2_crash_session_64B60356038900011FBAA1CFDA05C1CC_DNE_0_v2_stacktrace.txt](https://github.com/AppsFlyerSDK/appsflyer-android-app/files/12075706/com.alleylabs.battlegrounds_issue_058b6e64d49556d6cd96eb4c064927f2_crash_session_64B60356038900011FBAA1CFDA05C1CC_DNE_0_v2_stacktrace.txt)

**Comment by nitinberwal** [comment] 2023-07-19 05:19
We have increased appsflyer sdk version from 6.9.0 to 6.12.1. 

I am sharing stack trace that was received after crash

Caused by java.lang.IllegalAccessException: Class java.lang.Class<java.lang.reflect.Method> cannot access protected  method java.lang.Class com.appsflyer.internal.AFb1mSDK$$.loadClass(java.lang.String, boolean) of class java.lang.Class<com.appsflyer.internal.AFb1mSDK$$>
       at java.lang.reflect.Method.invokeImpl(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:411)
       at com.appsflyer.internal.AFb1mSDK$$.AFKeystoreWrapper(:100)
       at com.appsflyer.internal.AFb1mSDK$$.values(:19)
       at java.lang.reflect.Method.invokeImpl(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:411)
       at com.appsflyer.internal.AFb1pSDK.values(:125)
       at com.appsflyer.internal.AFd1eSDK.values(:9132)
       at com.appsflyer.internal.AFd1hSDK.values(:81)
       at com.appsflyer.internal.AFd1eSDK.AFKeystoreWrapper(:78)
       at com.appsflyer.internal.AFd1nSDK.AFInAppEventParameterName(:115)
       at com.appsflyer.internal.AFd1tSDK$5.run(:109)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)

**Comment by PickupAgency-Admin** [comment] 2023-07-19 16:24
Same problem here

Appsflyer SDK: com.appsflyer:af-android-sdk:6.11.1
target SDK: 33

- Crashes happen every time the SDK is initializing
- All affected devices are **rooted**
- errors occurs on Android 11, Android 8.1.0
- Devices Brand sample: OnePlus8Pro, Motorola One Vision, Xiaomi MI 9X, Samsung Galaxy A70, Huawei Enjoy 9s 
- RAM available: OK

```
Fatal Exception: java.lang.ExceptionInInitializerError:
       at com.appsflyer.AppsFlyerLib.getInstance()
       at com.myapp.App.initializeApplication(App.java:116)
       at com.myapp.App.onCreate(App.java:72)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1123)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5779)
       at android.app.ActivityThread.-wrap1()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1670)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6536)
       at java.lang.reflect.Method.invokeImpl(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:411)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:808)

Caused by java.lang.IllegalAccessException: Class java.lang.Class<java.lang.reflect.Method> cannot access protected  method java.lang.Class com.appsflyer.internal.AFa1zSDK$$.loadClass(java.lang.String, boolean) of class java.lang.Class<com.appsflyer.internal.AFa1zSDK$$>
       at java.lang.reflect.Method.invokeImpl(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:411)
       at com.appsflyer.internal.AFa1zSDK$$.values(:95)
       at com.appsflyer.internal.AFa1zSDK$$.AFInAppEventType(:2111)
       at java.lang.reflect.Method.invokeImpl(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:411)
       at com.appsflyer.internal.AFa1wSDK.AFKeystoreWrapper(:102)
       at com.appsflyer.internal.AFa1dSDK.values(SourceFile:50177)
       at com.appsflyer.internal.AFa1dSDK.<clinit>(:142)
       at com.appsflyer.AppsFlyerLib.getInstance()
       at com.myapp.App.initializeApplication(App.java:116)
       at com.myapp.App.onCreate(App.java:72)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1123)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5779)
       at android.app.ActivityThread.-wrap1()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1670)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6536)
       at java.lang.reflect.Method.invokeImpl(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:411)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:808)
```

**Comment by kashyap-5paisa** [comment] 2023-07-20 09:30
Any fix for this?? AppsFlyer Team, This is effecting our production application!! Needs quick resolution. Thanks in advance

**Comment by vladk-alike** [comment] 2023-07-20 13:28
I have the same problem. 
Do you know the version which works?

**Comment by ankitmaheswari** [comment] 2023-07-20 18:18
- Started with Appsflyer SDK version 6.11.1
- The affected device OnePlus 8Pro, Android OS 11, and the device is not rooted.
- App's Target SDK 33


Stacktrace:
```
Fatal Exception: java.lang.ExceptionInInitializerError:
       at com.appsflyer.internal.AFa1dSDK.valueOf(:242)
       at com.appsflyer.AppsFlyerLib.getInstance(:24)

Caused by java.lang.IllegalAccessException: Class java.lang.Class<java.lang.reflect.Method> cannot access protected  method java.lang.Class com.appsflyer.internal.AFa1zSDK$$.loadClass(java.lang.String, boolean) of class java.lang.Class<com.appsflyer.internal.AFa1zSDK$$>
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:423)
       at com.appsflyer.internal.AFa1zSDK$$.values(:95)
       at com.appsflyer.internal.AFa1zSDK$$.AFInAppEventType(:2111)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:423)
       at com.appsflyer.internal.AFa1wSDK.AFKeystoreWrapper(:103)
       at com.appsflyer.internal.AFa1dSDK.values(:50177)
       at com.appsflyer.internal.AFa1dSDK.<clinit>(:142)
       at com.appsflyer.internal.AFa1dSDK.valueOf(:242)
       at com.appsflyer.AppsFlyerLib.getInstance(:24)
```


The crash occurred for a user in intervals of 5 seconds.


Please share a fix version for this issue as soon as possible. This is impacting the app flows.

**Comment by af-fess** [comment] 2023-07-20 19:24
We plan to release a fix for this issue at the beginning of next week, version v6.12.2. This problem mostly occurs on rooted devices due to encrypted or obfuscated classes.

**Comment by kashyap-5paisa** [comment] 2023-07-26 05:58
Thanks @af-fess, When is the tentative release date for v6.12.2?

**Comment by ge-af** [comment] 2023-08-02 12:52
Hi, 
We've just released a new Android SDK version that fixes this issue.
The new version is v6.12.2.

**Closed as completed by ge-af** 2023-08-02 12:52 UTC
Labels: Support

**Comment by DevenHurt** [comment] 2023-08-03 02:44
> 

How can I access this version on react native? It doesn't seem to be available yet

**Comment by roblframpton** [comment] 2023-08-03 09:44
Great news, thanks for your hard work @ge-af and team!  Just waiting for a Flutter release now...

**Comment by MorganTrudeau** [comment] 2023-08-04 17:49
Thanks for the quick :)

**Comment by ge-af** [comment] 2023-08-06 05:29
Hi @roblframpton @DevenHurt 

We are working on updating the plugins at the moment. You can follow the designated Flutter and React Native repositories for more updates soon.

**Comment by reichhartd** [comment] 2023-08-07 08:04
Hi @ge-af 
I created a [pull request for React Native](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/pull/486) because this issue affects many of our users. Since we are releasing a new update tomorrow, could this PR be merged and released today? It's really not big and shouldn't take long to review.

**Comment by ashazar** [comment] 2023-08-08 07:17
> Hi @roblframpton @DevenHurt
> 
> We are working on updating the plugins at the moment. You can follow the designated Flutter and React Native repositories for more updates soon.

Hi @ge-af 

Thanks for the fix.

This includes `segment-android-integration` as well? Currently it's on v6.10.3

**Comment by jamesclement** [comment] 2023-08-10 14:31
Thanks for the fix here. Do we have an ETA on an update for `segment-android-integration` ?
